repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
-   repo: https://github.com/getcodelimit/codelimit
    rev: v0.2.1
    hooks:
    - id: codelimit
