[tool.poetry]
name = "sourcelimit"
version = "0.1.0"
description = ""
authors = ["Rob van der Leek <robvanderleek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pytest = "^7.2.0"


[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
