[tool.poetry]
name = "codelimit"
version = "0.1.0"
description = ""
authors = ["Rob van der Leek <robvanderleek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
halo = "^0.0.31"
plotext = "^5.2.8"
pygments = "^2.13.0"
textual = {extras = ["dev"], version = "^0.10.1"}

[tool.semantic_release]
version_variable = "codelimit/version.py:version"
branch = "main"
upload_to_repository = false
upload_to_release = false
build_command = "poetry build"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.6.1"
pytest-cov = "^4.0.0"
python-semantic-release = "^7.32.2"
pytest = "7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
