[tool.poetry]
name = "sourcelimit"
version = "0.1.0"
description = ""
authors = ["Rob van der Leek <robvanderleek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
halo = "^0.0.31"


[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.6.1"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
